### ISSUE TITLE
2-step join not working

### ISSUE THREAD

**Issue by SwiftShard** [DaveDuck321/KahootSmasher-NodeJS#1]
Everything works, and there are no fatal console errors, however no bots will join a Kahoot that has two-step join.
![image](https://user-images.githubusercontent.com/28634390/36358510-b2aba958-14dd-11e8-9b25-27a7450f7842.png)

**Comment by DaveDuck321** [comment]
I know but thanks for the feedback, that currently isn't a feature in the current kahoot smasher version either though. When I implement it there I'll port the changes over

**Comment by SwiftShard** [comment]
Ah, okay.
