### ISSUE TITLE
Bot not working.

### ISSUE THREAD

**Issue by PhippoGang** [DaveDuck321/KahootSmasher-NodeJS#3]
Upon replacing the http://localhost/start/kahoot-id/number-of-smashers/ with the kahoot ID and number of smashers, the webpage returns a message saying localhost refused to connect.

**Comment by DaveDuck321** [comment]
The address is http://localhost:3000/start/kahoot-id/number-of-smashers/, you missed the port number. I'm closing this issue for now, if its still a problem with the corrected address feel free to open a new one.
