### ISSUE TITLE
Improved Custom Names

### ISSUE THREAD

**Issue by danieldevofficial** [DaveDuck321/KahootSmasher-NodeJS#4]
It'd be a lot better if we could add custom names in the url
etc: (localhost/pin/amount/name).

**Comment by SwiftShard** [comment]
Just edit line 36 in [smasherBot.js](https://github.com/DaveDuck321/KahootSmasher-NodeJS/blob/master/smasherBot.js).

**Comment by danieldevofficial** [comment]
I know, but I prefer doing this using the address bar.

**Comment by CosminPerRam** [comment]
Do you mean to access something like `localhost/pin/amount/addname/John` and then automatically adds "John" to the entire name list? If not, please explain a little bit more of what you would want.

**Comment by danieldevofficial** [comment]
@CosminPerRam Basically, instead of manually adding a name to smasherBot.js you can go to 
localhost/pin/amount/namehere, and it'll that as the name.

**Comment by danieldevofficial** [comment]
@CosminPerRam Yh, that's what i mean :)

**Comment by danieldevofficial** [comment]
@CosminPerRam Great, lmk when it's done :)
