### ISSUE TITLE
On external server?

### ISSUE THREAD

**Issue by Wouterkaas** [DaveDuck321/KahootSmasher-NodeJS#5]
How can you do this on an external server? I use namecheap

**Comment by DaveDuck321** [comment]
As long as your hosting company provides you with a server which can install nodeJS this should work

**Comment by DaveDuck321** [comment]
No reply, I'm closing the thread

**Comment by Wouterkaas** [comment]
https://gyazo.com/eca0956f42951bb41c07cf7fc8fbb94c
https://gyazo.com/ff22ad504e46e3bf62e8256be01052ea
https://gyazo.com/100f297ffa1f036bb7900a76b27a0c1f
https://gyazo.com/e0f6d4f3833474876808840304915f6e

**Comment by DaveDuck321** [comment]
The server's address is localhost by default, to change it to your custom domain, you should edit line 49 in file start.js to the correct domain.

https://github.com/DaveDuck321/KahootSmasher-NodeJS/blob/d5c71167a906ecd3c264476b66413e763e6b9796/start.js#L49

Also, you will need to ensure that you can actually access port 3000 of the server, if you can't then you might need to replace the 3000 on this line with an accessible port like 80.

**Comment by Wouterkaas** [comment]
And if i want to add that you can use custom names that the url would be localhost:3000/start/gamepin/500/customname? I dont understand the code :)

**Comment by DaveDuck321** [comment]
This repo does not support custom names, if you want to edit them in, you can change line 36 in smasherBot.js and add your own names

https://github.com/DaveDuck321/KahootSmasher-NodeJS/blob/d5c71167a906ecd3c264476b66413e763e6b9796/smasherBot.js#L36
